### ISSUE TITLE
Mask doesn't work in Safari with client side rendering

### ISSUE THREAD

**Issue by HapLifeMan** [pqina/filepond-plugin-image-preview#11]
Hello,

I noticed today an issue with masks/gradients/idk on Safari with client side rendering.
I want to precise that I am using Nuxt with both client and server side rendering.

### Expectations

On Chrome, Firefox and Safari-(SSR-only), this is working fine:

![capture d ecran 2019-02-07 a 12 36 09](https://user-images.githubusercontent.com/1854141/52409186-057d2900-2ad5-11e9-905c-102eb668e1d4.png)

### Reality

But with client side rendering on Safari, I am switching to another page and go back to the previous, this is what I got and I don't understand what happened:

![capture d ecran 2019-02-07 a 12 36 25](https://user-images.githubusercontent.com/1854141/52409177-fdbd8480-2ad4-11e9-90c5-f22e869b4145.png)

### Comments

I don't know if it's a bug related to the library or not.
There's no error or warning in the console.
I found something that can be related, without success: https://fvsch.com/svg-gradient-fill/.
Can you help in that way? Thanks!

**Comment by rikschennink** [comment]
The image preview plugin generates an SVG element (when the file first loads) and adds it to the body, maybe it's removed on page switch?

**Comment by HapLifeMan** [comment]
I just verified and SVG elements are present and exactly the same for both client and server side rendering.

**Comment by rikschennink** [comment]
Okay, thanks! Can I test this publicly somewhere, I haven't been able to reproduce it locally.

**Comment by rikschennink** [comment]
Should be fixed with latest version of the plugin, please confirm.

**Comment by HapLifeMan** [comment]
It's working now @rikschennink, sorry for the delay! Thank you very much!
When I am resizing the window, the preview image is moving to black until I stop resizing.

![capture d ecran 2019-02-15 a 17 45 38](https://user-images.githubusercontent.com/1854141/52871239-e83a0180-3149-11e9-8b14-b6f8178ce6ad.png)

**Comment by rikschennink** [comment]
It does this to improve resizing performance. I’m still fine tuning to make it only do this if absolutely necessary.

I’ll close the issue as the original problem has been resolved.
