### ISSUE TITLE
Image preview flashes while scrolling on an iPhone

### ISSUE THREAD

**Issue by oldrich-s** [pqina/filepond-plugin-image-preview#13]
How to reproduce:

1. Use iPhone with latest iOS
2. Open https://pqina.nl/filepond/
3. Scroll to "Multiple File Upload"
4. Click on "Browse"
5. Select a picture
6. Wait until it loads
7. Swipe up and down
8. Observe how the image flashes

**Comment by rikschennink** [comment]
It's because the browser window is resized (vertically). It hides the images when this happens so it's faster to update the views.

**Comment by oldrich-s** [comment]
How can window be resized vertically when scrolling?

**Comment by rikschennink** [comment]
On iOs it is because it shows and hides the bottom menu bar which impacts the window height.

**Comment by oldrich-s** [comment]
I see, would it not make sense to exclude it from re-rendering? Something like:

![image](https://user-images.githubusercontent.com/37391/52856109-ccbc0000-3123-11e9-8865-12476b191c0e.png)

**Comment by rikschennink** [comment]
I'm looking into this now, but requesting `innerHeight` on each resize is performance intensive. Also, I want to stay away from fixed values. So I'm testing if the width is changing, should be fixed later today.

**Comment by oldrich-s** [comment]
ok, perfect 👍

**Comment by rikschennink** [comment]
Fixed in version `4.1.4`
