### ISSUE TITLE
How can we have a preview image at init with an existing image ?

### ISSUE THREAD

**Issue by Wifsimster** [pqina/filepond-plugin-image-preview#14]
Hi.

I'm working on a profil image and i initialize the filepond instance with the current image but the preview is not displayed ?

I read nothing on the documentation about init with a existing image, so is there a solution to do that ?

For the moment, i initialize my instance in the load process with a Blob.

**Comment by rikschennink** [comment]
You can set the initial files using the `files` property.
https://pqina.nl/filepond/docs/patterns/api/filepond-object/#setting-initial-files

If you've registered the image preview plugin it should automatically preview the file.

**Comment by Wifsimster** [comment]
Ok, thanks for the fast reply. This is actualy what i'm doing with a local path, triggering the load method.

In the load method, i'm calling the server to get my file (sendFile() with express on node.js), all good at this point. I'm loading my file through a `new Blob([response.data])` and filepond load the file but without the image preview.

![image](https://user-images.githubusercontent.com/644711/53037296-213fe200-347a-11e9-93d2-182b50519f5a.png)

**Comment by rikschennink** [comment]
Does your blob have type `image/jpeg`?

**Comment by Wifsimster** [comment]
Yes, it does.

`response` is my HTTP response from the server. `data` and `headers` are well valued.

```javascript
load(
  new Blob([response.data], {
    type: response.headers["content-type"]
  })
)
```

**Comment by rikschennink** [comment]
Can you supply a public test case

**Comment by Wifsimster** [comment]
I just make it work simplifying my load method with the object configuration.

Thank for the help, appreciate !

**Comment by rikschennink** [comment]
Glad to hear that, maybe share the solution so it might be a helpful issue for other devs?

**Comment by Wifsimster** [comment]
Sure !

My `files` property :

```javascript
this.files = [{ source: this.imagePath, options: { type: "local" } }];
```

And my working server configuration for init :
```javascript
{
  [...]
  load: {
    url: `?path=`,
      method: "GET",
      headers: {
        authorization: `Bearer ${localStorage.getItem("token")}`
      }
    }
}
```

**Comment by MrSunshyne** [comment]
@Wifsimster @rikschennink 

I hit the same issue. I'm providing it with the already uploaded image path, but there's no preview. It does load the 'filename' and 'filesize' though.

my files property :

```
  let initialFile = {
      source: this.imagePath,
      options: {
        type: 'local',
      },
    };

    this.files = [initialFile];
```

The filesize indicated is 2kb, and is not correct. 

I also added a simple img tag above filepond and gave it the same image path. That one loads, suggesting that the image link is correct and accessible. 

![image](https://user-images.githubusercontent.com/1721611/63088591-76ab0680-bf66-11e9-8541-3d65a7327529.png)

When I drag and drop an image on the filepond widget, i get an image preview. So i'm guessing the Image Preview Plugin is also correctly installed.

Any idea what i might have missed?

**Comment by rikschennink** [comment]
@MrSunshyne Have you configured the `server.load` endpoint?

**Comment by MrSunshyne** [comment]
@rikschennink 

wow. that did it!

```
server: {
        load: '/',
}
```

To be honest when I read the replies about [server load config ](https://github.com/pqina/filepond-plugin-image-preview/issues/14#issuecomment-465512926) and [server configuration](https://pqina.nl/filepond/docs/patterns/api/server/#configuration) in the docs, I thought these were supposed to be done on the server(backend). My bad.

It works now. Thanks !

**Comment by rikschennink** [comment]
@MrSunshyne fantastic, glad to hear that!

**Comment by aavram** [comment]
im trying to retrieve images stored on my server and it is working, however the file preview does not work; any idea of what i could be doing wrong?

**Comment by aavram** [comment]
I am getting files from the server and populating the files object; in the DOM i see a hidden input with value of my image url but the preview doesnt show my file.

**Comment by sjfarhanzaman** [comment]
I was facing the same issue with local files preview (after refresh)

So, I will post my solution for LAMP Stack:

Local File:
```php
$file =  [
            'source' => $filePath,
            'options' => [
                'type' => 'local',
                'fileSize' => $size,
            ]
        ];
```

Server Configuration:
```js
server: {
        process: {
           ...
           ...
        load: (source, load) => {
            $.ajax({
                url: '{{ url("/dashboard/creditworthiness/getFile") }}' + '/' + '{{ $activeApp->id }}' ,
                type: 'POST',
                data: {
                    source: source,
                },
                xhrFields: {
                    responseType: 'blob' // Set the response type to Blob
                },
                success: function(data) {
                    load(data);
                },
                error: function(xhr, status, error) {
                    console.error('AJAX request failed:', error);
                }
            });
        },
    },
```

Controller Method: 
```php
public function getFile($appID, $type)
    {
        $filePath = $_POST['source']; // Update the path accordingly

        $filename = basename($filePath);

        // get the mime type from file name extension
        $mime_type = mime_content_type($filePath);

        if (file_exists($filePath)) {
            $fileContent = file_get_contents($filePath);

            $response = new Response($fileContent, 200);
            $response->header('Access-Control-Expose-Headers', 'Content-Disposition, Content-Length, X-Content-Transfer-Id');
            $response->header('Content-Type', $mime_type);
            $response->header('Content-Disposition', 'inline; filename="' . $filename . '"');

            return $response;
        } else {
            return response()->json(['error' => 'File not found'], 404);
        }
    }
```

**Comment by MatiasBordoy** [comment]
I have a similar issue with the difference that i have the base64String of the File already  (or i can send the byte array)  (im not using an API).

And i can't initialize the image. I don't find anything in the app as an example of that.

I tried this with no luck:

`try {
    FilePond.registerPlugin(
        FilePondPluginFileValidateSize,
        FilePondPluginFileValidateType,
        FilePondPluginImageExifOrientation,
        FilePondPluginImagePreview,
        FilePondPluginImageCrop,
        FilePondPluginImageResize,
        FilePondPluginImageTransform,
    );

    let files = [];
    if (base64Image != '') {
        files = [
            {
                source: `data:${imageMimeType};base64,${base64Image}`,
                options: {
                    type: 'local'
                },
            }
        ];
    }

    const filePond = FilePond.create(
        document.getElementById(elementId),
        {
            element: null,
            allowFileSizeValidation: allowFileSizeValidation,
            minFileSize: minFileSize,
            maxFileSize: maxFileSize,
            maxTotalFileSize: maxTotalfileSize,
            imagePreviewHeight: imagePreviewHeight,
            imageCropAspectRatio: '1:1',
            imageResizeTargetWidth: imageResizeTargetWidth,
            imageResizeTargetHeight: imageResizeTargetHeight,
            stylePanelLayout: 'compact circle',
            styleLoadIndicatorPosition: 'center bottom',
            styleProgressIndicatorPosition: 'right bottom',
            styleButtonRemoveItemPosition: 'left bottom',
            styleButtonProcessItemPosition: 'right bottom',
            files: files,
        }
    );`
