### ISSUE TITLE
SVGs not previewing

### ISSUE THREAD

**Issue by matdave** [pqina/filepond-plugin-image-preview#17]
When I upload an SVG, it is not previewing.  I'm using the latest libraries from unpkg.

**Comment by matdave** [comment]
### Summary

When I upload an SVG to filepond, it is not previewing. This is also preventing Doka from being able to load. I'm using the latest libraries from unpkg.

### How to reproduce

Using the latest filepond add the FilePondPluginImagePreview, FilePondPluginImageEdit and Doka plugins and set `imageEditInstantEdit: true,`  

### Expected behaviour

Either dismiss SVG's or allow them to open in the image editor. 

### Full configuration

```
<script>
FilePond.registerPlugin(
    FilePondPluginImageCrop,
    FilePondPluginImageTransform,
    FilePondPluginImagePreview,
    FilePondPluginImageExifOrientation,
    FilePondPluginImageEdit,
    FilePondPluginFileValidateType,
    FilePondPluginFileValidateSize,
    FilePondPluginFileEncode
);
const iconElement = document.getElementById('extra-icon');
const iconPond = FilePond.create( iconElement , {
  allowMultiple: false,
  maxFiles: 1,
  labelIdle: "Drag & Drop your icon file or <span class=\"filepond--label-action\">Browse</span>",
  acceptedFileTypes: ['image/*'],
  fileValidateTypeDetectType: (source, type) => new Promise((resolve, reject) => {
      resolve(type);
  }),
  imageCropAspectRatio: '1:1',
  imageResizeTargetWidth: 500,
  imageResizeTargetHeight: 500,
  imageEditInstantEdit: false,
  maxFileSize: '5MB',
  imageEditEditor: Doka.create({
      outputFit: 'force',
      outputWidth: 400,
      outputHeight: 400,
      cropAspectRatioOptions: [
          {
              label: 'Square',
              value: 1
          },
      ]
  }),
});
</script>
```

**Comment by rikschennink** [comment]
Thanks, will look into this ASAP

**Comment by rikschennink** [comment]
I've quickly tried to open an SVG on `https://pqina.nl/filepond`, it seems to work correctly (note that both the FilePond library and image preview plugin have been recently updated. Am I missing something or has the issue accidentally been resolved?

**Comment by GiridharKarnik** [comment]
I can confirm that as of `"filepond": "^4.4.6", "filepond-plugin-image-preview": "^4.1.1"`, svgs are being previewed properly.
