### ISSUE TITLE
The preview plugin still shows wrong orientation when using in React app and image was restored from the server

### ISSUE THREAD

**Issue by dnknitro** [pqina/filepond-plugin-image-preview#19]
Please see issue @ https://github.com/pqina/filepond-plugin-image-exif-orientation/issues/2

**Comment by rikschennink** [comment]
Please don’t post duplicate issues.

**Comment by dnknitro** [comment]
I posted it to filepond-plugin-image-exif-orientation repo, but I was not sure which plugin is actually responsible for this behavior. After giving it a second though I think it is more about preview plugin than exif. Anyway, thanks for looking into this.
