### ISSUE TITLE
adding it in angular 6 

### ISSUE THREAD

**Issue by anymos** [pqina/filepond-plugin-image-preview#3]
isFile is not a function using the 

import FilePondPluginFileValidateType from 'filepond-plugin-file-validate-type';

// Import the plugin code
import FilepondPluginImagePreview from 'filepond-plugin-image-preview';
registerPlugin(FilepondPluginImagePreview);

registerPlugin(FilePondPluginFileValidateType);

and the ngx-filepond repo

Do not sound like production ready :-(

**Comment by rikschennink** [comment]
I've updated the FilePond library a week ago, this also required an update of the plugins and adapters ( to get the latest filepond dependency). 

Updating to the latest ngx-filepond version should do the trick.
