### ISSUE TITLE
Grid not visible

### ISSUE THREAD

**Issue by NielsLeenheer** [pqina/filepond-plugin-image-preview#32]
When grid is enabled using the `imagePreviewTransparencyIndicator` property, it does not show up. The reason is an error in CSS file.

The CSS file contains the following selector:
 `.filepond--image-preview[data-transparency-indicator='grid'] img, .filepond--image-preview[data-transparency-indicator='grid'] canvas`:
https://github.com/pqina/filepond-plugin-image-preview/blob/master/src/css/image-preview.scss#L17

So it assumes the dataset is on the `filepond--image-preview` element. But actually, the dataset is on the `filepond--image-clip` element, a child element of the `filepond--image-preview` element.

**Comment by rikschennink** [comment]
Thanks for reporting @NielsLeenheer, fixed in `4.6.2` 👍
