### ISSUE TITLE
IE11 Support

### ISSUE THREAD

**Issue by mneuhaus** [pqina/filepond-plugin-image-preview#4]
i know, it's ancient, but i think it could be supported with minimal effort, the main Problem is the dispatchEvent at the bottom :)

It fails with "Object doesn't support this action" which lead me here: https://stackoverflow.com/questions/27176983/dispatchevent-not-working-in-ie11

i "worked around" in my local installation with simply doing this: 

![](http://img.mia3.com//?i=1vIToIn8ql7GkHQ1.png)

any chance you could make this plugin work with IE11? :)

**Comment by rikschennink** [comment]
It should already work in IE11 :-)

Have you added the [polyfill package](https://github.com/pqina/filepond-polyfill)?

**Comment by rikschennink** [comment]
Closed because of no response. Local tests show image preview functions correctly.

**Comment by derekhewitt** [comment]
Sorry to open this back up,  I have tried with the polyfill package and am still not able to get it to work in IE 11, it looks like same as the screenshot below from your website. 
![image](https://user-images.githubusercontent.com/10667191/45862933-cb2f0d00-bd28-11e8-8f35-3ea6720e371b.png)

**Comment by rikschennink** [comment]
No problem @derekhewitt can you try adding:

```
<script src="https://cdnjs.cloudflare.com/ajax/libs/babel-core/5.6.15/browser-polyfill.min.js"></script>
```

**Comment by derekhewitt** [comment]
Thanks @rikschennink , that fixed the display issue.  Uploading a file now sticks on "waiting for size" with an error in the dev tools "Unhandled promise rejection error: incorrect function", even though I have the promise polyfill.

**Comment by rikschennink** [comment]
It's so strange because it does work in my test environment :)

I'm going to take a look at this over the weekend, will get back to you, ASAP.

**Comment by rikschennink** [comment]
@derekhewitt sorry for the delay.

I've just tested and it works fine on my IE11 VM with this setup:

```html
<script src="https://cdnjs.cloudflare.com/ajax/libs/babel-core/5.6.15/browser-polyfill.min.js"></script>

<script src="filepond-polyfill.min.js"></script>
<script src="filepond-plugin-image-preview.js"></script>
<script src="filepond.js"></script>

<script>
        FilePond.registerPlugin(FilePondPluginImagePreview);

        [].slice.call(document.querySelectorAll('input')).forEach(function(el) {
            const pond = FilePond.create(el,{
                server: 'http://192.168.33.11'
            });
        })
</script>

```

See screenshot, the version seems to be the same as yours.

![screen shot 2018-09-25 at 11 05 03](https://user-images.githubusercontent.com/1132575/46004345-ee541680-c0b2-11e8-9203-fb3a11274997.png)

**Comment by derekhewitt** [comment]
Thanks @rikschennink , I must have been doing something wrong - I was able to successful upload an image now.  Thanks for all your help.

**Comment by BMCwebdev** [comment]
For people who end up here searching for an answer to this or similar problems, I solved it by using the following:
https://www.npmjs.com/package/custom-event-polyfill
