### ISSUE TITLE
"IE11 and Vue.js" FilePond-plugin-Image-Preview doesn't work properly.

### ISSUE THREAD

**Issue by Shuya00** [pqina/filepond-plugin-image-preview#41]
Hi.
When using IE11 browser and vue-filepond, file-plugin-image-preview doesn't work properly.
It works when using original filepond and IE11.
It occurs only when I use vue-filepond and IE11.

If you upload an image, preview is almost good. (a little skewed)
but if you upload more images, preview gets corrupted.

I hope you could make this plugin work with IE11 and vue-filepond.

![vue-filepond_with_ie11](https://user-images.githubusercontent.com/73270268/96826877-4070ed00-146f-11eb-89a6-f409c4878823.JPG)

**Comment by rikschennink** [comment]
It works with IE11.

Have you set a doctype to your webpage?

**Comment by Shuya00** [comment]
Thank you for a quick reply.
OK, I use vuetify framework, so maybe I take a grammatically mistake of vuetify.
I'll review my code carefully.
It was good just to know that it works with IE11.
Thank you :)
