### ISSUE TITLE
Image problem after upload

### ISSUE THREAD

**Issue by xknght** [pqina/filepond-plugin-image-preview#55]
![obraz](https://user-images.githubusercontent.com/78901197/124401854-55a35880-dd2c-11eb-8561-3fc45f0efed2.png)

Any images it is inserted at the bottom of the page with a large margin. Version 4.5

```
<link rel="stylesheet" href="filepond.min.css">
<link ref="stylesheet" href="filepond-plugin-image-preview.css">
    <form>
        <input type="file" name="image" accept="image/png, image/gif, image/jpeg">
    </form>
        <script src="filepond-plugin-image-preview.js"></script>
        <script src="filepond.min.js"></script>
        <script>
            FilePond.registerPlugin(FilePondPluginImagePreview);
            const inputElement = document.querySelector('input[name="image"]');
            FilePond.create(inputElement);
        </script>
```

**Comment by rikschennink** [comment]
Looks like you're either not loading the preview styles correctly or your page doesn't have a doctype.

**Comment by xknght** [comment]
I tryied use other version filepond and plugins, non-min version. Document with BOM or not and nothing. Any suggestion ?

**Comment by rikschennink** [comment]
Please create a reproduction on codesandbox.io

**Comment by xknght** [comment]
> codesandbox.io

https://codesandbox.io/embed/relaxed-grothendieck-xkr0e?fontsize=14&hidenavigation=1&theme=dark

**Comment by xknght** [comment]
OMG ref -> rel Sorry 👯
