### ISSUE TITLE
Side by side

### ISSUE THREAD

**Issue by ronaldohoch** [pqina/filepond-plugin-image-preview#6]
Hello!
Is there a way to put the images in side by side?
![image](https://user-images.githubusercontent.com/2287371/43493261-69d390fa-9503-11e8-8568-9db62f1483de.png)

**Comment by rikschennink** [comment]
Currently there is not, but it’s on the roadmap for a future version.

**Comment by ronaldohoch** [comment]
@rikschennink, can You give me the way to implement it or a way to disable the transform translation property?

**Comment by rikschennink** [comment]
If I could I would have built it already. It needs serious testing as this would require a bigger drop area which would use up more GPU memory and stackin of items horizontally needs to be animated nicely as well. I would advice to either make multiple drop areas or make a single drop area that is less wide.

**Comment by rikschennink** [comment]
Duplicate of https://github.com/pqina/filepond/issues/134
