### ISSUE TITLE
Image preview image cover?

### ISSUE THREAD

**Issue by xHati44** [pqina/filepond-plugin-image-preview#69]
Hello, I was wondering if there was possibility to change the css of the preview to cover the space?
I wasn't able to find a solution.

![image](https://github.com/pqina/filepond-plugin-image-preview/assets/141344505/3a620576-2655-43df-89ec-4a40374f3389)

Thank you,

**Comment by rikschennink** [comment]
Set crop aspect ratio to `1`

**Comment by xHati44** [comment]
This worked, thank you!
