### ISSUE TITLE
how to add extra fields on preview?

### ISSUE THREAD

**Issue by bakamaru** [pqina/filepond-plugin-image-preview#8]
I want to add checkbox near with image preview. How can i achieve this.

**Comment by rikschennink** [comment]
It's currently not possible to modify the HTML, you'd have to fork the image-preview repository and build your own plugin.

**Comment by vesper8** [comment]
@rikschennink Hello. it's been 2+ years, is it possible to do anything with this now?

My use case is that I want to add an additional button to allow the user to "mark as main picture". So the user uploads up to 10 images, and then when clicking on an image, dead in the middle, it would call a function and mark that one as their main picture

Afterwards I would like that picture to be a bit different such as a ring or border around it to mark it as  the "main picture"

Is it possible to achieve this without forking?

Many thanks

**Comment by rikschennink** [comment]
@vesper8 No, fastest way is to create a custom plugin, that's what the plugins are for.
